apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-nvri
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-nvri
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-nvri
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-nvri
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-nvri
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/release-service-e2e-tenant/appstudio/dc-metro-map-nvri@sha256:ed0e616dc35adc1a523ff34f6538f0b4ea45e749a9dd6178673e53b725532025
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
